# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    session:
        handler_id: null
        storage_factory_id: 'session.storage.factory.native'
        cookie_secure: auto
    php_errors:
        log: true
