twig:
<<<<<<< HEAD
    file_name_pattern: '*.twig'
=======
    default_path: '%kernel.project_dir%/templates'
>>>>>>> e32fc08794f3f91c196b1f8bfe8205a51cb24ea2

when@test:
    twig:
        strict_variables: true
