when@dev:
    _errors:
<<<<<<< HEAD
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
=======
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
>>>>>>> e32fc08794f3f91c196b1f8bfe8205a51cb24ea2
        prefix: /_error
